### PR TITLE
Finish ballot count with question name/context

### PR DESCRIPTION
**Pull request by brianpchsu**

### CODE REVIEW

**Comment by bportnoy** [comment]
This looks good to me.

**Comment by brianpchsu** [comment]
This PR should wait until #72 merged since you both touch server/database/models/election.js

**Comment by rebekahkwon** [comment]
#72 merged. Looks good.

**Comment by rebekahkwon** [comment]
there are some merge conflicts, addressing them now.

**Comment by rebekahkwon** [comment]
thanks.

**Pull request merged**
